### ISSUE TITLE
Doesn't seem to function on Linux version of Stardew

### ISSUE THREAD

**Issue by HoodedDeath** [zunderscore/StardewWebApi#1] opened 2024-04-23 06:17 UTC
Maybe I'm stupid and did something wrong, but this mod doesn't appear to successfully open a listening port on Linux.

In the SMAPI log, it shows SMAPI loading the mod's DLL file, and the mod itself produces a trace level message saying "Starting web server", but my machine still refuses to connect on port 7882, which is the port I had found in the source when I glanced over it. I'm using V 0.4.0 from Nexus.

I've tried to use a web browser, curl, and a REST client application to try getting anything, and it just refuses connection.

Do I just have the wrong port or something obvious?

**Comment by zunderscore** [comment] 2024-04-23 13:08
Y'know, I haven't even tried running it on Linux yet. What distro are you using?

**Comment by HoodedDeath** [comment] 2024-04-23 13:22
I'm running on Arch. 

Are there any options in the release version that could provide more info for what's going on internally? If I can get some debug info or something I may be able to help track down/ fix whatever's going on with it

**Comment by zunderscore** [comment] 2024-04-23 13:45
No, not yet. Honestly, I just started putting this together 2 weeks ago so there isn't much debug/trace logging. I can take a look in my Ubuntu instance later when I get a few minutes and see if I can figure out what's up.

**Comment by HoodedDeath** [comment] 2024-04-23 13:48
Alright, sounds good. I might take a look at adding way too much debug logging tonight or tomorrow if I have time. Looking forward to updates.

**Comment by zunderscore** [comment] 2024-04-23 15:42
Looks like the issue is the IPv6 binding address not wanting to play nice on *nix systems. 0.4.1 will be out here in a few minutes with a fix, then I'll get it uploaded to Nexus.

**Comment by zunderscore** [comment] 2024-04-23 15:46
OK, [0.4.1](https://github.com/zunderscore/StardewWebApi/releases/0.4.1) is out and doing its thing on Nexus. Wanna give it a shot and see if you're able to get a response now?

`http://localhost:7882/mods` is a good test endpoint to hit once the game launches.

**Comment by HoodedDeath** [comment] 2024-04-23 21:51
Just gave it a quick test with /mods and /info/player and it seems to be working perfectly so far

**Comment by zunderscore** [comment] 2024-04-23 21:53
Awesome! I'll go ahead and close this as completed. Thanks for the report!

**Closed as completed by zunderscore** 2024-04-23 21:53 UTC
